### ISSUE TITLE
CDMA with Python libraries

### ISSUE THREAD

**Issue by patel999jay** [flandrade/communication-system-simulation#1]
Hi,

Thanks for your wonderful work. Sorry this is more than question than issue. Do you know any python libraries that i can use to design CDMA simulation by any chance ? Did you design just a simulation ? I mean to say if i want to implement this in real hardware how can i do this ?

Thanks.

**Comment by flandrade** [comment]
Thanks for taking a look. Unfortunately, this is only a simulation. I don't know if there are libraries to achieve that.
